spring.application.name=orderSystemDemo

# ===================================================================
# DataSource Settings
# ===================================================================
# ? MariaDB ??
spring.datasource.url=jdbc:mariadb://localhost:3306/esun_order_system?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
